### ISSUE TITLE
Fungerer dessverre ikke for meg

### ISSUE THREAD

**Issue by siljr** [sigvartmh/ITLscraper#2]
Får: 
Broken download link
og
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 34: ordinal not in range(128)

**Comment by sigvartmh** [comment]
Python versjon bruker du? Bruk python 3.5 og oppover helst

**Comment by siljr** [comment]
<img width="826" alt="screen shot 2017-05-14 at 17 24 18" src="https://cloud.githubusercontent.com/assets/5750523/26035292/3d9e0cfe-38ca-11e7-8265-d17b0243f0e5.png">

**Comment by sigvartmh** [comment]
Try ```pip3 install -r requirements

**Comment by sigvartmh** [comment]
```pip3 install -r requirements ```

**Comment by siljr** [comment]
Funka! :D
